import { mkdirSync, readFileSync, renameSync, writeFileSync } from 'fs';
import { randomUUID } from 'crypto';
import * as path from 'path';

/**
 * God's Land stage 5 (docs/product-reset/gods-land/03_PLAN.md): the smart clipboard. The helper sees a copy (when the
 * person turned history on, and never a password manager's — nspasteboard.org Concealed/Transient/AutoGenerated); this
 * decides what the copy IS and what it can become, and keeps the history. Everything here runs on the Mac: no model is
 * asked, nothing is sent anywhere.
 *
 * - colour  → hex, rgb(), hsl(), SwiftUI Color, and the nearest Tailwind class;
 * - JSON    → minified, pretty, and a TypeScript type (inferred here, deterministically);
 * - link    → the same link without tracking parameters (our own list, research 02 §4: ClearURLs' is LGPL);
 * - code    → its language, and one line for shell and SQL;
 * - anything that looks like a secret key is NOT kept at all until stage 6 can mask it (looksSecret).
 * Ghost Paste is not here: the owner dropped it (03, decision 1).
 */

export type ClipKind = 'color' | 'json' | 'url' | 'code' | 'text';
export interface ClipAction { label: string; value: string }
export interface ClipCard { id: string; kind: ClipKind; preview: string; text: string; detail?: string; swatch?: string; actions: ClipAction[]; pinned: boolean; source?: string }
export interface ClipView { t: 'clips'; enabled: boolean; items: ClipCard[] }

// ── Colours ──────────────────────────────────────────────────────────────────────────────────────────────────────────

export interface Rgb { r: number; g: number; b: number; a: number }

const clamp = (x: number, lo: number, hi: number): number => Math.min(hi, Math.max(lo, x));
const hex2 = (n: number): string => Math.round(clamp(n, 0, 255)).toString(16).padStart(2, '0');
const alphaOf = (raw: string | undefined): number => (raw === undefined ? 1 : clamp(raw.endsWith('%') ? parseFloat(raw) / 100 : parseFloat(raw), 0, 1));

export function parseColor(text: string): Rgb | null {
  const t = text.trim().toLowerCase();
  let m = /^#([0-9a-f]{3}|[0-9a-f]{6}|[0-9a-f]{8})$/.exec(t);
  if (m) {
    let h = m[1]!;
    if (h.length === 3) h = h.split('').map((c) => c + c).join('');
    const a = h.length === 8 ? parseInt(h.slice(6, 8), 16) / 255 : 1;
    return { r: parseInt(h.slice(0, 2), 16), g: parseInt(h.slice(2, 4), 16), b: parseInt(h.slice(4, 6), 16), a };
  }
  m = /^rgba?\(\s*(\d{1,3})\s*[, ]\s*(\d{1,3})\s*[, ]\s*(\d{1,3})\s*(?:[,/]\s*([\d.]+%?)\s*)?\)$/.exec(t);
  if (m) {
    const [r, g, b] = [m[1], m[2], m[3]].map(Number) as [number, number, number];
    if (r > 255 || g > 255 || b > 255) return null;
    return { r, g, b, a: alphaOf(m[4]) };
  }
  m = /^hsla?\(\s*([\d.]+)(?:deg)?\s*[, ]\s*([\d.]+)%\s*[, ]\s*([\d.]+)%\s*(?:[,/]\s*([\d.]+%?)\s*)?\)$/.exec(t);
  if (m) {
    const h = (parseFloat(m[1]!) % 360) / 360;
    const s = clamp(parseFloat(m[2]!) / 100, 0, 1);
    const l = clamp(parseFloat(m[3]!) / 100, 0, 1);
    const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
    const p = 2 * l - q;
    const f = (x: number): number => {
      const y = ((x % 1) + 1) % 1;
      return y < 1 / 6 ? p + (q - p) * 6 * y : y < 1 / 2 ? q : y < 2 / 3 ? p + (q - p) * (2 / 3 - y) * 6 : p;
    };
    return { r: Math.round(f(h + 1 / 3) * 255), g: Math.round(f(h) * 255), b: Math.round(f(h - 1 / 3) * 255), a: alphaOf(m[4]) };
  }
  return null;
}

export function toHex(c: Rgb): string { return `#${hex2(c.r)}${hex2(c.g)}${hex2(c.b)}${c.a < 1 ? hex2(c.a * 255) : ''}`; }
export function toRgb(c: Rgb): string { return c.a < 1 ? `rgb(${c.r} ${c.g} ${c.b} / ${+c.a.toFixed(2)})` : `rgb(${c.r}, ${c.g}, ${c.b})`; }
export function toHsl(c: Rgb): string {
  const r = c.r / 255, g = c.g / 255, b = c.b / 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b), l = (max + min) / 2, d = max - min;
  let h = 0, s = 0;
  if (d) {
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    h = max === r ? (g - b) / d + (g < b ? 6 : 0) : max === g ? (b - r) / d + 2 : (r - g) / d + 4;
    h *= 60;
  }
  return `hsl(${Math.round(h)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%${c.a < 1 ? ` / ${+c.a.toFixed(2)}` : ''})`;
}
export function toSwiftUI(c: Rgb): string {
  const f = (n: number): string => { const v = +(n / 255).toFixed(3); return Number.isInteger(v) ? v.toFixed(1) : String(v); };
  return `Color(red: ${f(c.r)}, green: ${f(c.g)}, blue: ${f(c.b)}${c.a < 1 ? `, opacity: ${+c.a.toFixed(2)}` : ''})`;
}

/** Tailwind CSS v3.4.17's default palette (src/public/colors.js, MIT, Tailwind Labs) — shades 50…950. */
const TAILWIND: Record<string, string[]> = {
  slate: ['#f8fafc', '#f1f5f9', '#e2e8f0', '#cbd5e1', '#94a3b8', '#64748b', '#475569', '#334155', '#1e293b', '#0f172a', '#020617'],
  gray: ['#f9fafb', '#f3f4f6', '#e5e7eb', '#d1d5db', '#9ca3af', '#6b7280', '#4b5563', '#374151', '#1f2937', '#111827', '#030712'],
  zinc: ['#fafafa', '#f4f4f5', '#e4e4e7', '#d4d4d8', '#a1a1aa', '#71717a', '#52525b', '#3f3f46', '#27272a', '#18181b', '#09090b'],
  neutral: ['#fafafa', '#f5f5f5', '#e5e5e5', '#d4d4d4', '#a3a3a3', '#737373', '#525252', '#404040', '#262626', '#171717', '#0a0a0a'],
  stone: ['#fafaf9', '#f5f5f4', '#e7e5e4', '#d6d3d1', '#a8a29e', '#78716c', '#57534e', '#44403c', '#292524', '#1c1917', '#0c0a09'],
  red: ['#fef2f2', '#fee2e2', '#fecaca', '#fca5a5', '#f87171', '#ef4444', '#dc2626', '#b91c1c', '#991b1b', '#7f1d1d', '#450a0a'],
  orange: ['#fff7ed', '#ffedd5', '#fed7aa', '#fdba74', '#fb923c', '#f97316', '#ea580c', '#c2410c', '#9a3412', '#7c2d12', '#431407'],
  amber: ['#fffbeb', '#fef3c7', '#fde68a', '#fcd34d', '#fbbf24', '#f59e0b', '#d97706', '#b45309', '#92400e', '#78350f', '#451a03'],
  yellow: ['#fefce8', '#fef9c3', '#fef08a', '#fde047', '#facc15', '#eab308', '#ca8a04', '#a16207', '#854d0e', '#713f12', '#422006'],
  lime: ['#f7fee7', '#ecfccb', '#d9f99d', '#bef264', '#a3e635', '#84cc16', '#65a30d', '#4d7c0f', '#3f6212', '#365314', '#1a2e05'],
  green: ['#f0fdf4', '#dcfce7', '#bbf7d0', '#86efac', '#4ade80', '#22c55e', '#16a34a', '#15803d', '#166534', '#14532d', '#052e16'],
  emerald: ['#ecfdf5', '#d1fae5', '#a7f3d0', '#6ee7b7', '#34d399', '#10b981', '#059669', '#047857', '#065f46', '#064e3b', '#022c22'],
  teal: ['#f0fdfa', '#ccfbf1', '#99f6e4', '#5eead4', '#2dd4bf', '#14b8a6', '#0d9488', '#0f766e', '#115e59', '#134e4a', '#042f2e'],
  cyan: ['#ecfeff', '#cffafe', '#a5f3fc', '#67e8f9', '#22d3ee', '#06b6d4', '#0891b2', '#0e7490', '#155e75', '#164e63', '#083344'],
  sky: ['#f0f9ff', '#e0f2fe', '#bae6fd', '#7dd3fc', '#38bdf8', '#0ea5e9', '#0284c7', '#0369a1', '#075985', '#0c4a6e', '#082f49'],
  blue: ['#eff6ff', '#dbeafe', '#bfdbfe', '#93c5fd', '#60a5fa', '#3b82f6', '#2563eb', '#1d4ed8', '#1e40af', '#1e3a8a', '#172554'],
  indigo: ['#eef2ff', '#e0e7ff', '#c7d2fe', '#a5b4fc', '#818cf8', '#6366f1', '#4f46e5', '#4338ca', '#3730a3', '#312e81', '#1e1b4b'],
  violet: ['#f5f3ff', '#ede9fe', '#ddd6fe', '#c4b5fd', '#a78bfa', '#8b5cf6', '#7c3aed', '#6d28d9', '#5b21b6', '#4c1d95', '#2e1065'],
  purple: ['#faf5ff', '#f3e8ff', '#e9d5ff', '#d8b4fe', '#c084fc', '#a855f7', '#9333ea', '#7e22ce', '#6b21a8', '#581c87', '#3b0764'],
  fuchsia: ['#fdf4ff', '#fae8ff', '#f5d0fe', '#f0abfc', '#e879f9', '#d946ef', '#c026d3', '#a21caf', '#86198f', '#701a75', '#4a044e'],
  pink: ['#fdf2f8', '#fce7f3', '#fbcfe8', '#f9a8d4', '#f472b6', '#ec4899', '#db2777', '#be185d', '#9d174d', '#831843', '#500724'],
  rose: ['#fff1f2', '#ffe4e6', '#fecdd3', '#fda4af', '#fb7185', '#f43f5e', '#e11d48', '#be123c', '#9f1239', '#881337', '#4c0519'],
};
const SHADES = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];

/** The nearest Tailwind colour class (a redmean distance, closer to the eye than plain RGB); exact when in the palette. */
export function nearestTailwind(c: Rgb): { name: string; exact: boolean } {
  let best = { name: '', distance: Infinity };
  for (const [family, hexes] of Object.entries(TAILWIND)) {
    hexes.forEach((hex, i) => {
      const p = parseColor(hex)!;
      const rMean = (p.r + c.r) / 2;
      const distance = (2 + rMean / 256) * (p.r - c.r) ** 2 + 4 * (p.g - c.g) ** 2 + (2 + (255 - rMean) / 256) * (p.b - c.b) ** 2;
      if (distance < best.distance) best = { name: `${family}-${SHADES[i]}`, distance };
    });
  }
  return { name: best.name, exact: best.distance === 0 };
}

// ── Links ────────────────────────────────────────────────────────────────────────────────────────────────────────────

/** Parameters that only track the click. Our own list: well-known, generic, and not ClearURLs' (LGPL, 02 §4). */
const TRACKING = new Set([
  'fbclid', 'gclid', 'dclid', 'gbraid', 'wbraid', 'msclkid', 'yclid', 'twclid', 'ttclid', 'li_fat_id', 'igshid', 'igsh',
  'mc_cid', 'mc_eid', '_hsenc', '_hsmi', 'hsctatracking', 'mkt_tok', 'vero_id', 'vero_conv', 'oly_anon_id', 'oly_enc_id',
  'rb_clickid', 's_cid', 'ncid', 'sr_share', 'spm', 'scm', 'si', 'ref_src', 'ref_url', 'trk', 'trkcampaign',
]);

/** The link without tracking parameters, or null when there was nothing to remove. Non-http(s) links are left alone. */
export function cleanUrl(text: string): string | null {
  let url: URL;
  try { url = new URL(text.trim()); } catch { return null; }
  if (url.protocol !== 'http:' && url.protocol !== 'https:') return null;
  const drop = [...url.searchParams.keys()].filter((k) => TRACKING.has(k.toLowerCase()) || /^utm_/i.test(k) || /^pk_/i.test(k));
  if (!drop.length) return null;
  for (const key of drop) url.searchParams.delete(key);
  return url.toString().replace(/\?$/, '').replace(/\?#/, '#');
}

// ── JSON → TypeScript ───────────────────────────────────────────────────────────────────────────────────────────────

const IDENT = /^[A-Za-z_$][\w$]*$/;
const pascal = (key: string): string =>
  key.replace(/[^A-Za-z0-9]+(.)?/g, (_: string, c: string | undefined) => (c ? c.toUpperCase() : '')).replace(/^./, (c) => c.toUpperCase()) || 'Item';

/** A TypeScript type for a JSON value: nested objects become named interfaces, arrays merge their elements' shapes. */
export function jsonToTypeScript(value: unknown, rootName = 'Root'): string {
  const interfaces: string[] = [];
  const used = new Set<string>();
  const nameFor = (base: string): string => { let n = base; let i = 2; while (used.has(n)) n = `${base}${i++}`; used.add(n); return n; };
  const objectType = (fields: Record<string, unknown[]>, count: number, base: string): string => {
    const name = nameFor(pascal(base));
    const lines = Object.entries(fields).map(([key, values]) => {
      const types = [...new Set(values.map((x) => typeOf(x, key)))];
      return `  ${IDENT.test(key) ? key : JSON.stringify(key)}${values.length < count ? '?' : ''}: ${types.join(' | ')};`;
    });
    interfaces.push(`export interface ${name} {\n${lines.join('\n')}\n}`);
    return name;
  };
  const typeOf = (v: unknown, name: string): string => {
    if (v === null) return 'null';
    if (Array.isArray(v)) {
      if (!v.length) return 'unknown[]';
      if (v.every((e) => e && typeof e === 'object' && !Array.isArray(e))) {
        const merged: Record<string, unknown[]> = {};
        for (const e of v as Record<string, unknown>[]) for (const [k, x] of Object.entries(e)) (merged[k] ??= []).push(x);
        return `${objectType(merged, v.length, name.replace(/s$/, '') || name)}[]`;
      }
      const types = [...new Set(v.map((e) => typeOf(e, name)))];
      return types.length === 1 ? `${types[0]}[]` : `(${types.join(' | ')})[]`;
    }
    if (typeof v === 'object') return objectType(Object.fromEntries(Object.entries(v as object).map(([k, x]) => [k, [x]])), 1, name);
    return typeof v === 'number' || typeof v === 'boolean' || typeof v === 'string' ? typeof v : 'unknown';
  };
  const root = typeOf(value, rootName);
  const out = [...interfaces];
  if (root !== pascal(rootName)) out.push(`export type ${nameFor(rootName)} = ${root};`);
  return out.join('\n\n');
}

// ── Code ─────────────────────────────────────────────────────────────────────────────────────────────────────────────

const LANGUAGES: Array<[string, RegExp]> = [
  ['SQL', /^\s*(select\s[\s\S]+\sfrom\s|insert\s+into\s|update\s+\w+\s+set\s|delete\s+from\s|create\s+(table|index|view)\s)/i],
  ['Shell', /^\s*(\$\s|sudo\s|brew\s|npm\s|npx\s|pnpm\s|yarn\s|git\s|cd\s|ls\b|curl\s|docker\s|kubectl\s|export\s+\w+=|pip3?\s|python3?\s+-m\s|chmod\s|mkdir\s)/],
  ['Swift', /\b(import (SwiftUI|Foundation|AppKit|UIKit)|guard let |func \w+\(.*\)\s*->\s*\w+\s*\{)/],
  ['Rust', /\b(fn \w+\(|let mut |impl\s+\w+|pub fn |use std::)/],
  ['Go', /\b(package main|func \w+\(.*\)\s*\{|:= |import \()/],
  ['Python', /^\s*(def \w+\(.*\):|class \w+.*:|import \w+\s*$|from \w+ import )/m],
  ['TypeScript', /\b(interface \w+\s*\{|type \w+ =|: (string|number|boolean)\b|as const\b)/],
  ['JavaScript', /\b(function \w*\(|const \w+ = |let \w+ = |=>\s*\{|console\.log\(|require\()/],
  ['C/C++', /#include\s*[<"]|\bint main\(|std::/],
  ['HTML', /^\s*<(!doctype|html|div|span|a |p>|section|head|body)/i],
  ['CSS', /^[\s.#\w-]+\{[^}]*:[^}]*;[^}]*\}/],
];

export function codeLanguage(text: string): string | null {
  const t = text.trim();
  if (t.length < 4) return null;
  for (const [name, pattern] of LANGUAGES) if (pattern.test(t)) return name;
  return null;
}

/** One line for shell (backslash continuations and lines joined with &&) and SQL (whitespace collapsed). */
export function oneLine(text: string, language: string): string | null {
  const t = text.trim();
  if (!t.includes('\n')) return null;
  if (language === 'Shell') return t.replace(/[ \t]*\\\n\s*/g, ' ').split('\n').map((l) => l.trim().replace(/^\$\s+/, '')).filter(Boolean).join(' && ');
  if (language === 'SQL') return t.replace(/\s+/g, ' ');
  return null;
}

// ── Secrets (kept out until stage 6) ────────────────────────────────────────────────────────────────────────────────

/** The most common credential shapes (after gitleaks' rules, MIT): these are not kept in the history at all. */
const SECRET = [
  /\bAKIA[0-9A-Z]{16}\b/, /\b(sk|pk|rk)_(live|test)_[0-9A-Za-z]{16,}\b/, /\bgh[pousr]_[A-Za-z0-9]{36,}\b/, /\bgithub_pat_[A-Za-z0-9_]{50,}\b/,
  /\bxox[abpors]-[A-Za-z0-9-]{10,}\b/, /-----BEGIN (RSA |EC |OPENSSH |DSA |PGP )?PRIVATE KEY-----/, /\bAIza[0-9A-Za-z_-]{35}\b/,
  /\bsk-(proj-|ant-)?[A-Za-z0-9_-]{20,}\b/, /\bnvapi-[A-Za-z0-9_-]{20,}\b/, /\beyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b/,
  /\b[a-z][a-z0-9+.-]*:\/\/[^\s:/@]+:[^\s@/]{3,}@/i,
];
export function looksSecret(text: string): boolean { return SECRET.some((p) => p.test(text)); }

// ── What a copy is ───────────────────────────────────────────────────────────────────────────────────────────────────

export function classify(text: string): Omit<ClipCard, 'id' | 'pinned' | 'source'> {
  const t = text.trim();
  const first = t.split('\n')[0]!;
  const preview = first.slice(0, 80) + (t.length > first.length || first.length > 80 ? '…' : '');
  const color = parseColor(t);
  if (color) {
    const tw = nearestTailwind(color);
    return { kind: 'color', preview: t, text, swatch: toHex(color), detail: tw.exact ? tw.name : `≈ ${tw.name}`, actions: [
      { label: 'HEX', value: toHex(color) }, { label: 'RGB', value: toRgb(color) }, { label: 'HSL', value: toHsl(color) },
      { label: 'Swift', value: toSwiftUI(color) }, { label: tw.exact ? 'Tailwind' : 'Tailwind ≈', value: `bg-${tw.name}` },
    ] };
  }
  if (/^[[{]/.test(t)) {
    try {
      const value = JSON.parse(t) as unknown;
      if (value && typeof value === 'object') {
        const count = Array.isArray(value) ? `${value.length} items` : `${Object.keys(value).length} keys`;
        return { kind: 'json', preview, text, detail: `JSON · ${count}`, actions: [
          { label: 'Minify', value: JSON.stringify(value) }, { label: 'Pretty', value: JSON.stringify(value, null, 2) },
          { label: 'TS type', value: jsonToTypeScript(value) },
        ] };
      }
    } catch { /* not JSON */ }
  }
  if (/^https?:\/\/\S+$/i.test(t)) {
    let host = '';
    try { host = new URL(t).hostname; } catch { /* kept as text */ }
    if (host) {
      const cleaned = cleanUrl(t);
      return { kind: 'url', preview: t.slice(0, 80), text, detail: cleaned ? `${host} · tracking removed` : host, actions: cleaned ? [{ label: 'Clean link', value: cleaned }] : [] };
    }
  }
  const language = codeLanguage(t);
  if (language) {
    const single = oneLine(t, language);
    return { kind: 'code', preview, text, detail: language, actions: single ? [{ label: 'One line', value: single }] : [] };
  }
  return { kind: 'text', preview, text, actions: [] };
}

// ── The history ─────────────────────────────────────────────────────────────────────────────────────────────────────

export const MAX_CLIPS = 50;
export const MAX_CLIP_CHARS = 20_000;
export const CLIPS_SHOWN = 12;
interface StoredClip { id: string; text: string; at: number; pinned?: boolean; source?: string }

/**
 * The last MAX_CLIPS copies, newest first, pinned ones kept past the limit. Saved on this Mac only, in the app's data
 * folder. Unlike the shelf this is a history: the oldest unpinned copy makes room for a new one.
 */
export class ClipHistory {
  private clips: StoredClip[] = [];

  constructor(private readonly file: string, private readonly now: () => number = Date.now) {
    try {
      const parsed = JSON.parse(readFileSync(file, 'utf8')) as { clips?: StoredClip[] };
      this.clips = Array.isArray(parsed.clips) ? parsed.clips.filter((c) => c && typeof c.id === 'string' && typeof c.text === 'string') : [];
    } catch { this.clips = []; }
  }

  private save(): void {
    mkdirSync(path.dirname(this.file), { recursive: true });
    const temp = `${this.file}.${process.pid}.tmp`;
    writeFileSync(temp, JSON.stringify({ version: 1, clips: this.clips }));
    renameSync(temp, this.file);
  }

  /** Keep a copy. Returns false for what is never kept: empty, too long, or shaped like a secret. */
  add(text: string, source?: string): boolean {
    if (!text.trim() || text.length > MAX_CLIP_CHARS || looksSecret(text)) return false;
    const existing = this.clips.find((c) => c.text === text);
    if (existing) {
      existing.at = this.now();
      if (source) existing.source = source;
    } else {
      this.clips.push({ id: randomUUID(), text, at: this.now(), ...(source ? { source } : {}) });
    }
    const unpinned = this.clips.filter((c) => !c.pinned).sort((a, b) => b.at - a.at);
    const drop = new Set(unpinned.slice(MAX_CLIPS).map((c) => c.id));
    this.clips = this.clips.filter((c) => !drop.has(c.id));
    this.save();
    return true;
  }

  pin(id: string, pinned: boolean): boolean {
    const clip = this.clips.find((c) => c.id === id);
    if (!clip) return false;
    if (pinned) clip.pinned = true;
    else delete clip.pinned;
    this.save();
    return true;
  }

  remove(id: string): boolean {
    const before = this.clips.length;
    this.clips = this.clips.filter((c) => c.id !== id);
    if (this.clips.length === before) return false;
    this.save();
    return true;
  }

  /** Pinned first, then newest; each with what it is and what it can become. */
  view(enabled: boolean): ClipView {
    const ordered = [...this.clips].sort((a, b) => Number(!!b.pinned) - Number(!!a.pinned) || b.at - a.at).slice(0, CLIPS_SHOWN);
    return { t: 'clips', enabled, items: ordered.map((c) => ({ id: c.id, pinned: !!c.pinned, ...(c.source ? { source: c.source } : {}), ...classify(c.text) })) };
  }
}
