import * as fs from 'fs';
import * as path from 'path';
import { readPdf } from './pdf.raster';
import { ocrPages } from './ocr';

/**
 * Universal text extraction with provenance.
 *
 * The Composer's premise is that a user drops *whatever they have* — a scanned inspection report, a
 * vendor quote, a spreadsheet of thickness readings, a shutdown punch list, a P&ID photo — and the
 * system reads it. That is only useful if every extracted fragment can say where it came from:
 * an approval note citing "corrosion at nozzle N2" is worthless to an inspection engineer unless it
 * also says *E-204 Inspection Report.pdf, page 3*. So extraction never returns a bare string. It
 * returns SEGMENTS, each carrying a locator, and the retrieval layer keeps that locator attached all
 * the way to the model's context window.
 *
 * Design notes worth keeping:
 *
 * 1. **A segment is a natural unit of the source, not a fixed size.** A PDF page, a spreadsheet
 *    sheet, a slide (plus its speaker notes), a text file. Chunking to a token budget happens later
 *    and downstream — splitting here would destroy the locator, because a 1,200-character window
 *    that straddles pages 3 and 4 can be honestly cited as neither.
 *
 * 2. **Extraction must degrade, never throw.** One unreadable file in a 200-file shutdown drop must
 *    not fail the drop. Every extractor reports `ok: false` with a reason and the corpus records it,
 *    so the user is told "191 of 200 ingested, 9 skipped, here is why" instead of silence.
 *
 * 3. **Nothing here reaches the network.** OCR is Apple Vision or Tesseract, both local; the Office
 *    formats are ZIP containers parsed in-process. This file is safe under `--sovereign`.
 */

/** Where a fragment came from, in the source's own coordinates. */
export interface Locator {
  /** 1-indexed page, for paged formats. */
  page?: number;
  /** Worksheet name, for spreadsheets. */
  sheet?: string;
  /** 1-indexed slide number, for presentations. */
  slide?: string | number;
  /** A named section, for formats that have them. */
  section?: string;
}

export interface Segment {
  text: string;
  locator: Locator;
  /**
   * A short line that must ride on EVERY chunk cut from this segment, not just the first.
   *
   * This is the deterministic half of Contextual Retrieval (measured: prepending chunk-specific
   * context cuts top-20 retrieval failures 5.7% -> 2.9%, and 1.9% with reranking). The failure it
   * removes is the dominant one for engineering documents: a spreadsheet is ONE segment, so when it
   * is chunked only the first chunk keeps the header row — every later chunk becomes a grid of bare
   * numbers whose columns are unnamed and whose equipment is unstated. Error analysis of
   * text-and-table retrieval puts 73% of residual failures in exactly that class.
   *
   * Deliberately derived from the document, never generated by a model: it must run at ingest speed
   * on an air-gapped box.
   */
  context?: string;
  /** How the text was obtained. `ocr` means it was *read from an image* and may contain errors. */
  via: 'text' | 'text-layer' | 'ocr' | 'cells' | 'xml';
  /** Mean OCR confidence 0..1, when the segment came from a recognizer. */
  confidence?: number;
}

export interface ExtractionResult {
  ok: boolean;
  file: string;
  /** Lower-case extension including the dot, or '' when the file has none. */
  kind: string;
  segments: Segment[];
  /** Human-readable reason when `ok` is false, or a caveat when it is true. */
  note?: string;
  bytes: number;
}

/** Formats we parse structurally rather than by sniffing. */
const PDF = new Set(['.pdf']);
const IMAGE = new Set(['.png', '.jpg', '.jpeg', '.gif', '.webp', '.bmp', '.tif', '.tiff', '.heic']);
const SHEET = new Set(['.xlsx', '.xlsm', '.xltx']);
const CSVISH = new Set(['.csv', '.tsv']);
const DOCX = new Set(['.docx', '.docm']);
const PPTX = new Set(['.pptx', '.pptm']);

/**
 * Extensions that are archives, executables or media we cannot read as text. Sniffing these wastes
 * time and, worse, a binary that happens to pass the printable-ratio test injects garbage into
 * retrieval that outranks real content on rare-token matches.
 */
const OPAQUE = new Set([
  '.zip', '.tar', '.gz', '.bz2', '.xz', '.7z', '.rar', '.dmg', '.iso', '.pkg',
  '.exe', '.dll', '.so', '.dylib', '.o', '.a', '.class', '.jar', '.wasm',
  '.mp4', '.mov', '.avi', '.mkv', '.webm', '.mp3', '.wav', '.m4a', '.flac', '.ogg',
  '.ttf', '.otf', '.woff', '.woff2', '.eot',
  '.db', '.sqlite', '.sqlite3', '.mdb', '.bin', '.dat', '.pyc', '.lock',
]);

/** Hard ceiling per file. A 500 MB log is not a document; ingesting it evicts everything useful. */
const MAX_BYTES = 64 * 1024 * 1024;
/** Cap on text taken from any one file, after extraction. */
const MAX_CHARS = 8 * 1024 * 1024;

function clean(value: string): string {
  // Normalise the whitespace OCR and XML extraction both produce in abundance, and drop the control
  // characters that survive PDF text layers. Keeps chunk boundaries meaningful.
  return value
    .replace(/\r\n?/g, '\n')
    // eslint-disable-next-line no-control-regex
    .replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, ' ')
    .replace(/[ \t]+\n/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

/**
 * Is this buffer text?
 *
 * A NUL byte is the classic binary tell and costs nothing to check. Beyond that we require most
 * bytes to be printable: a file that is 30% control characters is a binary that happens to contain
 * some ASCII, and admitting it pollutes retrieval. UTF-16 text (a BOM plus alternating NULs) is
 * recognised rather than rejected, because Windows-authored refinery logs are routinely UTF-16.
 */
export function looksLikeText(buffer: Buffer): { text: boolean; encoding: BufferEncoding } {
  if (buffer.length === 0) return { text: false, encoding: 'utf8' };
  if (buffer[0] === 0xff && buffer[1] === 0xfe) return { text: true, encoding: 'utf16le' };
  if (buffer[0] === 0xef && buffer[1] === 0xbb && buffer[2] === 0xbf) return { text: true, encoding: 'utf8' };

  const sample = buffer.subarray(0, Math.min(buffer.length, 8192));
  let printable = 0;
  let nul = 0;
  for (const byte of sample) {
    if (byte === 0) nul++;
    else if (byte === 9 || byte === 10 || byte === 13 || (byte >= 32 && byte !== 127)) printable++;
  }
  if (nul > sample.length * 0.01) return { text: false, encoding: 'utf8' };
  return { text: printable / sample.length > 0.85, encoding: 'utf8' };
}

/** ZIP central-directory reader. docx/pptx/xlsx are all ZIP containers of XML. */
async function unzipEntries(file: string, wanted: (name: string) => boolean): Promise<Map<string, string>> {
  // jszip is already in the dependency tree and parses in-process with no temp files, which keeps
  // an Office document's contents off disk — it may be confidential.
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const JSZip = require('jszip');
  const zip = await JSZip.loadAsync(await fs.promises.readFile(file));
  const out = new Map<string, string>();
  const names: string[] = Object.keys(zip.files);
  for (const name of names) {
    if (!wanted(name) || zip.files[name].dir) continue;
    out.set(name, await zip.files[name].async('string'));
  }
  return out;
}

/** Strip XML tags to readable text, preserving paragraph and cell boundaries as newlines/tabs. */
function xmlToText(xml: string): string {
  return xml
    // Word/PowerPoint break elements become real breaks before the tags are stripped.
    .replace(/<\/w:p>|<\/a:p>|<w:br\b[^>]*\/?>|<a:br\b[^>]*\/?>/g, '\n')
    .replace(/<\/w:tc>|<\/a:tc>/g, '\t')
    .replace(/<\/w:tr>|<\/a:tr>/g, '\n')
    .replace(/<[^>]+>/g, '')
    .replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_m, d) => String.fromCharCode(Number(d)));
}

async function extractPdf(file: string): Promise<Segment[]> {
  // readPdf already does the right thing: embedded text layer FIRST, rasterise + OCR only the pages
  // that have none. A born-digital report costs no OCR; a scanned one is recognised page by page.
  const result = await readPdf(file);
  const needOcr = result.pages.filter((p) => !p.text && p.imagePath);
  const recognized = new Map<string, { text: string; confidence?: number }>();
  if (needOcr.length) {
    const { pages } = await ocrPages(needOcr.map((p) => p.imagePath!));
    for (const page of pages) recognized.set(page.imagePath, { text: page.text, confidence: page.confidence });
  }
  const segments: Segment[] = [];
  for (const page of result.pages) {
    if (page.text && page.text.trim()) {
      const cleaned = clean(page.text);
      segments.push({ text: cleaned, locator: { page: page.page }, via: 'text-layer', context: leadingContext(cleaned) });
      continue;
    }
    const hit = page.imagePath ? recognized.get(page.imagePath) : undefined;
    if (hit && hit.text.trim()) {
      const cleaned = clean(hit.text);
      segments.push({ text: cleaned, locator: { page: page.page }, via: 'ocr', confidence: hit.confidence, context: leadingContext(cleaned) });
    }
  }
  return segments;
}

async function extractImage(file: string): Promise<Segment[]> {
  const { pages } = await ocrPages([file]);
  const page = pages[0];
  if (!page || !page.text.trim()) return [];
  return [{ text: clean(page.text), locator: {}, via: 'ocr', confidence: page.confidence }];
}

async function extractSheet(file: string, isCsv: boolean): Promise<Segment[]> {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const ExcelJS = require('exceljs');
  const workbook = new ExcelJS.Workbook();
  if (isCsv) await workbook.csv.readFile(file);
  else await workbook.xlsx.readFile(file);

  const segments: Segment[] = [];
  workbook.eachSheet((sheet: any) => {
    const rows: string[] = [];
    sheet.eachRow({ includeEmpty: false }, (row: any) => {
      const cells: string[] = [];
      row.eachCell({ includeEmpty: true }, (cell: any) => {
        const value = cell?.value;
        if (value === null || value === undefined) { cells.push(''); return; }
        // A formula cell carries both the formula and its last computed result; the RESULT is the
        // measurement an engineer means. `=B4-C4` retrieves nothing useful; `7.8` does.
        if (typeof value === 'object' && 'result' in value) { cells.push(String(value.result ?? '')); return; }
        if (typeof value === 'object' && 'text' in value) { cells.push(String((value as any).text ?? '')); return; }
        if (value instanceof Date) { cells.push(value.toISOString().slice(0, 10)); return; }
        cells.push(String(value));
      });
      const line = cells.join('\t').trimEnd();
      if (line.trim()) rows.push(line);
    });
    if (rows.length) {
      // The first row of a worksheet is its column names in almost every real workbook. Losing it
      // turns "7.8" into an uninterpretable number; carrying it makes every chunk self-describing.
      const header = rows[0].split('\t').some((cell) => /[A-Za-z]/.test(cell)) ? rows[0] : undefined;
      segments.push({
        text: clean(rows.join('\n')),
        locator: { sheet: sheet.name },
        via: 'cells',
        context: header ? `columns: ${header.replace(/\t/g, ' | ')}` : undefined,
      });
    }
  });
  return segments;
}

async function extractDocx(file: string): Promise<Segment[]> {
  const entries = await unzipEntries(file, (n) =>
    n === 'word/document.xml' || /^word\/(header|footer)\d*\.xml$/.test(n));
  const body = entries.get('word/document.xml');
  const segments: Segment[] = [];
  if (body) {
    const text = clean(xmlToText(body));
    if (text) segments.push({ text, locator: { section: 'body' }, via: 'xml' });
  }
  for (const [name, xml] of entries) {
    if (name === 'word/document.xml') continue;
    const text = clean(xmlToText(xml));
    // Headers and footers carry the document control numbers and revision stamps an approval note
    // has to quote, so they are kept — but as their own segment, not spliced into the body.
    if (text) segments.push({ text, locator: { section: path.basename(name, '.xml') }, via: 'xml' });
  }
  return segments;
}

async function extractPptx(file: string): Promise<Segment[]> {
  const entries = await unzipEntries(file, (n) =>
    /^ppt\/slides\/slide\d+\.xml$/.test(n) || /^ppt\/notesSlides\/notesSlide\d+\.xml$/.test(n));
  const slides = new Map<number, { body: string; notes: string }>();
  for (const [name, xml] of entries) {
    const match = name.match(/(\d+)\.xml$/);
    if (!match) continue;
    const index = Number(match[1]);
    const entry = slides.get(index) ?? { body: '', notes: '' };
    if (name.includes('notesSlides')) entry.notes = clean(xmlToText(xml));
    else entry.body = clean(xmlToText(xml));
    slides.set(index, entry);
  }
  return [...slides.entries()]
    .sort((a, b) => a[0] - b[0])
    .map(([index, { body, notes }]) => ({
      // Speaker notes routinely hold the reasoning the slide only asserts, which is exactly what a
      // later question ("why did we defer that repair?") needs to retrieve.
      text: notes ? `${body}\n\n[Speaker notes]\n${notes}`.trim() : body,
      locator: { slide: index },
      via: 'xml' as const,
    }))
    .filter((segment) => segment.text.trim().length > 0);
}

async function extractPlainText(file: string, bytes: number): Promise<{ segments: Segment[]; note?: string }> {
  const buffer = await fs.promises.readFile(file);
  const { text, encoding } = looksLikeText(buffer);
  if (!text) return { segments: [], note: 'not text (binary content)' };
  let content = clean(buffer.toString(encoding));
  let note: string | undefined;
  if (content.length > MAX_CHARS) {
    content = content.slice(0, MAX_CHARS);
    note = `truncated to ${MAX_CHARS} characters (source was ${bytes} bytes)`;
  }
  if (!content) return { segments: [], note: 'file is empty after normalisation' };
  return { segments: [{ text: content, locator: {}, via: 'text', context: leadingContext(content) }], note };
}

/**
 * Extract one file. Never throws for a content reason — a failure is a result with `ok: false`.
 */
export async function extractFile(file: string): Promise<ExtractionResult> {
  const kind = path.extname(file).toLowerCase();
  const base: Omit<ExtractionResult, 'ok' | 'segments'> = { file, kind, bytes: 0 };

  let stat: fs.Stats;
  try {
    stat = await fs.promises.stat(file);
  } catch (error) {
    return { ...base, ok: false, segments: [], note: `cannot read: ${(error as Error).message}` };
  }
  if (stat.isDirectory()) return { ...base, ok: false, segments: [], note: 'is a directory' };
  base.bytes = stat.size;
  if (stat.size === 0) return { ...base, ok: false, segments: [], note: 'file is empty' };
  if (stat.size > MAX_BYTES) {
    return { ...base, ok: false, segments: [], note: `larger than the ${MAX_BYTES / 1024 / 1024} MB ingest limit` };
  }
  if (OPAQUE.has(kind)) {
    return { ...base, ok: false, segments: [], note: `${kind} is not a readable document format` };
  }

  try {
    if (PDF.has(kind)) return { ...base, ok: true, segments: await extractPdf(file) };
    if (IMAGE.has(kind)) return { ...base, ok: true, segments: await extractImage(file) };
    if (SHEET.has(kind)) return { ...base, ok: true, segments: await extractSheet(file, false) };
    if (CSVISH.has(kind)) return { ...base, ok: true, segments: await extractSheet(file, true) };
    if (DOCX.has(kind)) return { ...base, ok: true, segments: await extractDocx(file) };
    if (PPTX.has(kind)) return { ...base, ok: true, segments: await extractPptx(file) };
    // Everything else — .md, .txt, source code, .json, .yaml, .log, and the genuinely unknown
    // `.xyz` an instrument vendor invented — goes through the sniffer.
    const { segments, note } = await extractPlainText(file, stat.size);
    return { ...base, ok: segments.length > 0, segments, note };
  } catch (error) {
    return { ...base, ok: false, segments: [], note: `extraction failed: ${(error as Error).message}` };
  }
}

/**
 * The opening line of a segment, when it looks like a title rather than prose.
 *
 * On a repetitive form the equipment identity sits at the top of the page ("INSPECTION RECORD
 * SHEET. Equipment E-204."), and every chunk below the first loses it. Carrying it forward is what
 * lets a query naming the vessel reach the chunk holding its measurement.
 */
export function leadingContext(text: string): string | undefined {
  const first = text.split('\n').map((line) => line.trim()).find((line) => line.length > 0);
  if (!first) return undefined;
  // A long paragraph is prose, not a heading; repeating it on every chunk would bloat the index
  // and add no identifying signal.
  if (first.length > 160) return first.slice(0, 160);
  return first;
}

/** Render a locator the way it should appear in a citation. */
export function describeLocator(locator: Locator): string {
  const parts: string[] = [];
  if (locator.page !== undefined) parts.push(`page ${locator.page}`);
  if (locator.sheet !== undefined) parts.push(`sheet ${locator.sheet}`);
  if (locator.slide !== undefined) parts.push(`slide ${locator.slide}`);
  if (locator.section !== undefined) parts.push(locator.section);
  return parts.join(' · ');
}
