// God's Land stage 5: the smart clipboard (docs/product-reset/gods-land/03_PLAN.md). The app decides what a copy is
// and what it can become (app/src/main/clipboard.ts); this watches for copies — only while the person has history on —
// and draws the history.
//
// Watching: macOS sends no notification when the clipboard changes, so the change count is read about twice a second
// (what every clipboard manager does; Maccy's default is similar), and only while history is on. Reading the change
// count shows no prompt; reading the text is what macOS's pasteboard privacy may ask about once (02 §2).
//
// Never kept: anything a password manager marks Concealed, Transient or AutoGenerated (nspasteboard.org), and the
// notch's own copies. The app additionally refuses anything shaped like a secret key.
//
// Protocol additions:
//   in   {"t":"clip-config","enabled":bool}   {"t":"clips","enabled":bool,"items":[card]}
//        card = {"id","kind":"color|json|url|code|text","preview","text","detail?","swatch?","actions":[{"label","value"}],"pinned","source?"}
//   out  {"t":"clip","text","source?"}  {"t":"clip-enable"}  {"t":"clip-disable"}  {"t":"clip-pin","id","pinned"}  {"t":"clip-remove","id"}

import AppKit
import SwiftUI

struct ClipAction: Equatable, Hashable {
    let label: String
    let value: String
}

struct ClipCard: Identifiable, Equatable {
    let id: String
    let kind: String
    let preview: String
    let text: String
    let detail: String?
    let swatch: String?
    let actions: [ClipAction]
    let pinned: Bool

    init?(json row: [String: Any]) {
        guard let id = row["id"] as? String, let kind = row["kind"] as? String, let text = row["text"] as? String else { return nil }
        self.id = id
        self.kind = kind
        self.text = text
        self.preview = row["preview"] as? String ?? text
        self.detail = row["detail"] as? String
        self.swatch = row["swatch"] as? String
        self.actions = (row["actions"] as? [[String: Any]] ?? []).compactMap { a in
            guard let label = a["label"] as? String, let value = a["value"] as? String else { return nil }
            return ClipAction(label: label, value: value)
        }
        self.pinned = row["pinned"] as? Bool ?? false
    }

    var symbol: String {
        switch kind {
        case "json": return "curlybraces"
        case "url": return "link"
        case "code": return "chevron.left.forwardslash.chevron.right"
        default: return "text.alignleft"
        }
    }
}

final class ClipboardWatch {
    /// nspasteboard.org markers: a password manager's copy is never recorded.
    static let neverKept: Set<String> = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]

    static func shouldSkip(types: [String]) -> Bool { types.contains(where: neverKept.contains) }

    /// What macOS says about this app reading the clipboard (macOS 15.4+), for the notch to explain a refusal.
    static var accessBehavior: String {
        if #available(macOS 15.4, *) {
            switch NSPasteboard.general.accessBehavior {
            case .alwaysAllow: return "alwaysAllow"
            case .alwaysDeny: return "alwaysDeny"
            case .ask: return "ask"
            default: return "default"
            }
        }
        return "alwaysAllow"
    }

    private let board: NSPasteboard
    private var timer: Timer?
    private var lastCount: Int
    private var ownCount = -1

    /// `board` is the general clipboard; the self-test passes a private one so it never touches the person's.
    init(board: NSPasteboard = .general) {
        self.board = board
        lastCount = board.changeCount
    }
    var copied: (String, String?) -> Void = { _, _ in }

    var running: Bool { timer != nil }

    func start() {
        guard timer == nil else { return }
        // Start from now: turning history on does not sweep in whatever was copied before.
        lastCount = board.changeCount
        let timer = Timer(timeInterval: 0.6, repeats: true) { [weak self] _ in self?.check() }
        timer.tolerance = 0.3 // let macOS coalesce the wake-ups
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func check() {
        let count = board.changeCount
        guard count != lastCount else { return }
        lastCount = count
        guard count != ownCount else { return }
        let types = board.types?.map(\.rawValue) ?? []
        guard !Self.shouldSkip(types: types), let text = board.string(forType: .string), !text.isEmpty else { return }
        copied(text, NSWorkspace.shared.frontmostApplication?.localizedName)
    }

    /// The notch wrote the clipboard itself (a shelf copy): do not record that write.
    func markOwnWrite() { ownCount = board.changeCount }

    /// Put `text` on the clipboard for the person to paste, without recording it again.
    func copy(_ text: String) {
        board.clearContents()
        board.setString(text, forType: .string)
        ownCount = board.changeCount
    }
}

// MARK: - Views

enum NotchTab: String, CaseIterable {
    case now = "Now", shelf = "Shelf", recall = "Recall", clipboard = "Clipboard", secrets = "Secrets"
}

struct TabChips: View {
    @ObservedObject var model: NotchModel

    var body: some View {
        HStack(spacing: 4) {
            ForEach(NotchTab.allCases, id: \.self) { tab in
                Button(tab.rawValue) { model.tab = tab }
                    .buttonStyle(TabStyle(selected: model.tab == tab))
                    .accessibilityAddTraits(model.tab == tab ? .isSelected : [])
            }
        }
    }
}

struct TabStyle: ButtonStyle {
    let selected: Bool

    func makeBody(configuration: Configuration) -> some View {
        configuration.label
            .font(.system(size: 10.5, weight: selected ? .semibold : .medium))
            .foregroundStyle(Color.white.opacity(selected ? 1 : notchSecondary))
            .padding(.horizontal, 8).padding(.vertical, 3)
            .background(Capsule().fill(Color.primary.opacity(selected ? 0.16 : (configuration.isPressed ? 0.1 : 0))))
    }
}

enum ClipCommand {
    case copy(String), pin(ClipCard), remove(ClipCard), enable
}

struct ClipboardSection: View {
    @ObservedObject var model: NotchModel
    let run: (ClipCommand) -> Void

    var body: some View {
        if model.clipAccess == "alwaysDeny" {
            explainer("macOS is set to refuse Bimax the clipboard. To keep a history, allow Bimax under System Settings › Privacy & Security › Paste from Other Apps.")
        } else if !model.clipEnabled {
            VStack(alignment: .leading, spacing: 8) {
                explainer("Keep a history of what you copy — colours, JSON, links and code become one-tap conversions. It stays on this Mac, and a password manager's copies are never kept.\(model.clipAccess == "ask" || model.clipAccess == "default" ? " macOS may ask once to allow it." : "")")
                Button("Turn On Clipboard History") { run(.enable) }.buttonStyle(ChipStyle())
            }
        } else if model.clips.filter({ $0.kind != "secret" }).isEmpty {
            explainer("Copy something and it appears here.")
        } else {
            VStack(spacing: 3) {
                // Secrets are kept sealed and live on the Secrets tab, where they can be revealed or copied.
                ForEach(model.clips.filter { $0.kind != "secret" }.prefix(6)) { clip in ClipRow(clip: clip, run: run) }
            }
        }
    }

    private func explainer(_ text: String) -> some View {
        Text(text).font(.system(size: 11)).foregroundStyle(Color.white.opacity(notchSecondary)).fixedSize(horizontal: false, vertical: true)
    }
}

struct ClipRow: View {
    let clip: ClipCard
    let run: (ClipCommand) -> Void

    private var swatch: Color? {
        guard let hex = clip.swatch, hex.count >= 7, let value = UInt64(hex.dropFirst().prefix(6), radix: 16) else { return nil }
        return Color(red: Double((value >> 16) & 0xff) / 255, green: Double((value >> 8) & 0xff) / 255, blue: Double(value & 0xff) / 255)
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 4) {
            Button { run(.copy(clip.text)) } label: {
                HStack(spacing: 8) {
                    if let swatch {
                        RoundedRectangle(cornerRadius: 4, style: .continuous).fill(swatch).frame(width: 16, height: 16)
                            .overlay(RoundedRectangle(cornerRadius: 4, style: .continuous).strokeBorder(Color.primary.opacity(0.25), lineWidth: 0.5))
                    } else {
                        Image(systemName: clip.symbol).font(.system(size: 11)).foregroundStyle(Color.white.opacity(notchSecondary)).frame(width: 16)
                    }
                    VStack(alignment: .leading, spacing: 1) {
                        Text(clip.preview).font(.system(size: 11.5, design: clip.kind == "code" || clip.kind == "json" ? .monospaced : .default))
                            .foregroundStyle(.primary).lineLimit(1)
                        if let detail = clip.detail {
                            Text(detail).font(.system(size: 10)).foregroundStyle(Color.white.opacity(notchSecondary)).lineLimit(1)
                        }
                    }
                    Spacer(minLength: 0)
                    if clip.pinned { Image(systemName: "pin.fill").font(.system(size: 9)).foregroundStyle(Color.white.opacity(notchSecondary)) }
                }
                .contentShape(Rectangle())
            }
            .buttonStyle(RowButtonStyle())
            .accessibilityLabel("\(clip.preview)\(clip.detail.map { ", \($0)" } ?? ""). Copies it.")
            if !clip.actions.isEmpty {
                ScrollView(.horizontal, showsIndicators: false) {
                    HStack(spacing: 4) {
                        ForEach(clip.actions, id: \.self) { action in
                            Button(action.label) { run(.copy(action.value)) }.buttonStyle(ChipStyle())
                                .accessibilityLabel("Copy as \(action.label)")
                        }
                    }
                    .padding(.leading, 30)
                }
            }
        }
        .contextMenu {
            Button(clip.pinned ? "Unpin" : "Pin") { run(.pin(clip)) }
            Button("Remove from History") { run(.remove(clip)) }
        }
    }
}
